### ISSUE TITLE
Design initial database schema

### ISSUE THREAD

**Issue by sarahdagger** [ubclaunchpad/floradora#2]
Design an initial database scheme to support our MVP. At a minimum, we will need to store information about:
- Users account data (eg. username, email, etc.)
- Image data (eg. id, size, image type, S3 bucket link, etc.)
- Classification data (eg. reference to image, classification, degree of certainty, etc.)

Create an intial [Entity Relationship Diagram](https://www.lucidchart.com/pages/er-diagrams) to define each data model/table we will need, as well as the relationships between the different data models (note: draw.io is a useful tool to create UML diagrams like this, but feel free to use whichever tool you like).

**Comment by wu-jacob** [comment]
Current schema:
![Virtual_Collection](https://user-images.githubusercontent.com/99063771/218279281-1a48b126-02f9-4cca-a9b9-eaf9f1e3b942.png)

**Comment by wu-jacob** [comment]
Most likely using PostgreSQL
