### ISSUE TITLE
Research relevant datasets

### ISSUE THREAD

**Issue by sarahdagger** [ubclaunchpad/floradora#6]
Research ML datasets related to the following:
- Classification of different plant species
- Classification of different animal species (eg. a dataset of North American mammals or different bird species)
- Classification of different animal breeds within a species (eg. dog breeds)

Maintain a list of of the most promising datasets and record the size of the dataset, whether the images are pre-labeled, if they are used in existing projects, and/or any other data that seems relevant in choosing a dataset.

**Comment by zhanginc** [comment]
Research Notes:
https://impartial-sound-ba3.notion.site/Image-Recognition-Dataset-7413a00e76f944d6a18a61e8ad03a75a
